title: Human Robot Systems (HRS)-Reading Group
author: Yohei Hayamizu
email: yhayami1@binghamton.edu

description: >-
  We are a pioneering research group at Binghamton University focused on advancing human-robot systems.
  Our weekly meetings bring together students and faculty to explore cutting-edge developments in robotics,
  artificial intelligence, and human-robot interaction.

baseurl: "/hrs-reading-group"
url: "https://YoheiHayamizu.github.io"
homepage_link: https://robotics.cs.binghamton.edu/
github_username: bu-air-lab

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom settings
future: true # Publish future dated posts
show_excerpts: true # Show excerpts on the homepage
header_pages: # Add links to pages in the site header
  - about.md
  - research.md
  - publications.md
  - tags.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      paper_type: "Research Paper"

# Add collections for different types of content
collections:
  reading_sessions:
    output: true
    permalink: /sessions/:path/
